// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    DarkToggleButton: typeof import('./src/components/slides/DarkToggleButton.vue')['default']
    FluidCalc: typeof import('./src/components/FluidCalc.vue')['default']
    HeroHome: typeof import('./src/components/HeroHome.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Marker: typeof import('./src/components/slides/Marker.vue')['default']
    MarkerCore: typeof import('./src/components/slides/MarkerCore.vue')['default']
    MarkerPattern: typeof import('./src/components/slides/MarkerPattern.vue')['default']
    MarkerTips: typeof import('./src/components/slides/MarkerTips.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    Pricing: typeof import('./src/components/Pricing.vue')['default']
    RiArticleLine: typeof import('virtual:vite-icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('virtual:vite-icons/ri/bookmark-line')['default']
    RiLightbulbLine: typeof import('virtual:vite-icons/ri/lightbulb-line')['default']
    RiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    RiStickyNoteLine: typeof import('virtual:vite-icons/ri/sticky-note-line')['default']
    RiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
    Slidev: typeof import('./src/components/icones/Slidev.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    VueDemi: typeof import('./src/components/icones/VueDemi.vue')['default']
    VueFooter: typeof import('./src/components/VueFooter.vue')['default']
    VueReactivity: typeof import('./src/components/icones/VueReactivity.vue')['default']
    VueUse: typeof import('./src/components/icones/VueUse.vue')['default']
    VueUseFn: typeof import('./src/components/slides/VueUseFn.vue')['default']
  }
}

export { }
