export const bundles: Array<any> = [
  {
    name: 'Minimum Database',
    cost: 350,
    value: 1000,
    description:
      'This bundle is run on all admitted patients, or on those patients where a minimum database is required either pre-consultation or as part of a consultation to help decide if a patient requires admission for further investigation.',
    items: [
      'Packed Cell Volume (PCV)',
      'Total Proteins (TSP)',
      'Blood Gas Analysis',
      'Lactate',
      'Electrolytes including ionised Calcium',
      'Urea',
      'Creatinine',
      'Bedside Ultrasound (A-FAST, T-FAST, Vet-BLUE)',
      'SpO2',
      'Remote Support',
    ],
  },
  {
    name: 'Get Well Sooner not Later',
    cost: 950,
    value: 1500,
    description:
      'Would you like to feel sick for twice the time, or do you want to get well sooner? Admission for treatment of a known condition where further diagnostics are not indicated and treatment is supportive. Perfect for the dehydrated gastroenteritis',
    items: [
      'Packed Cell Volume (PCV)',
      'Total Proteins (TSP)',
      'Blood Gas Analysis',
      'Lactate',
      'Electrolytes including ionised Calcium',
      'Urea',
      'Creatinine',
      'Bedside Ultrasound (A-FAST, T-FAST, Vet-BLUE)',
      'Remote Support',
      'Hospital Admission',
      'Tailored treatment plan',
      'IV catheter placement',
      'IV fluid plan',
      'IV fluid therapy',
      'Injectable pain relief',
      'Antiemetics',
      'Gastric Protection',
      'SpO2',
      'Blood Pressure',
    ],
  },
  {
    name: 'Not Right & Not Sure',
    cost: 1750,
    value: 2500,
    description:
      'Not sure what is wrong, but sure its not doing right? Admission on this bundle provides diagnostics and treatment and will provide a clear direction if not a clear diagnosis in most of your patients who present, not doing quite right',
    items: [
      'Packed Cell Volume (PCV)',
      'Total Proteins (TSP)',
      'Blood Gas Analysis',
      'Lactate',
      'Electrolytes including ionised Calcium',
      'Urea',
      'Creatinine',
      'Bedside Ultrasound (A-FAST, T-FAST, Vet-BLUE)',
      'Remote Support',
      'Hospital Admission',
      'Tailored treatment plan',
      'IV catheter placement',
      'IV fluid plan',
      'IV fluid therapy',
      'Injectable pain relief',
      'Antiemetics',
      'Gastric Protection',
      'Thoracic Radiographs',
      'Abdominal Radiographs',
      'Radiographic Assessment and reporting through SignalPet',
      'Tertiary opinion on radiographs via Clinical Support',
      'Full Abdominal Ultrasound In-house',
      'CBC',
      'Biochemistry',
      'c-Reactive Protein',
      'pro-BNP',
      'snap-cPLI',
      'Parvo Test',
      'T4',
      'FIV/FeLV',
      'PT/APTT',
      'SpO2',
      'Blood Pressure',
    ],
  },
  {
    name: 'Sick for Sure, Lets Get to It',
    cost: 2250,
    value: 3500,
    description:
      'Not sure what is wrong, but sure its not doing right? Admission on this bundle provides diagnostics and treatment and will provide a clear direction if not a clear diagnosis in most of your patients who present, not doing quite right',
    items: [
      'Packed Cell Volume (PCV)',
      'Total Proteins (TSP)',
      'Blood Gas Analysis',
      'Lactate',
      'Electrolytes including ionised Calcium',
      'Urea',
      'Creatinine',
      'Bedside Ultrasound (A-FAST, T-FAST, Vet-BLUE)',
      'Remote Support',
      'Hospital Admission',
      'Tailored treatment plan',
      'IV catheter placement',
      'IV fluid plan',
      'IV fluid therapy',
      'Injectable pain relief',
      'Antiemetics',
      'Gastric Protection',
      'Thoracic Radiographs',
      'Abdominal Radiographs',
      'Radiographic Assessment and reporting through SignalPet',
      'Extended Ultrasound with Dr Kerri Renshaw',
      'Tertiary opinion on radiographs via Clinical Support',
      'CBC',
      'Biochemistry',
      'c-Reactive Protein',
      'snap-cPLI',
      'pro-BNP',
      'SpO2',
      'Blood Pressure',
      'Parvo Test',
      'T4',
      'FIV/FeLV',
      'PT/APTT',
      'Analgesia CRIs',
      'Minor Procedures',
      'External Lab Fees up to $300',
      'q2h nursing care',
      'Consultant input and case management by Senior Qualified Clinical Team',
    ],
  },
]
